name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Setup dotnet
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2
        with:
          dotnet-version: "7.0.x"

      - name: Publish release
        run: |
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x64 --self-contained false -o release/win-x64/lw
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x64 --self-contained true -o release/win-x64/sc
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x86 --self-contained false -o release/win-x86/lw
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x86 --self-contained true -o release/win-x86/sc

      - name: Zip release files
        run: |
          zip -j release/warm-corners_x64.zip release/win-x64/lw/WarmCorners.exe release/win-x64/lw/appsettings.json
          zip -j release/warm-corners_x64_sc.zip release/win-x64/sc/WarmCorners.exe release/win-x64/sc/appsettings.json
          zip -j release/warm-corners_x86.zip release/win-x86/lw/WarmCorners.exe release/win-x86/lw/appsettings.json
          zip -j release/warm-corners_x86_sc.zip release/win-x86/sc/WarmCorners.exe release/win-x86/sc/appsettings.json

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            release/warm-corners_x64.zip
            release/warm-corners_x64_sc.zip
            release/warm-corners_x86.zip
            release/warm-corners_x86_sc.zip