name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Setup dotnet
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2
        with:
          dotnet-version: "7.0.x"

      - name: Publish release
        run: |
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x64 --self-contained false -o release/win-x64/lw
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x64 --self-contained true -o release/win-x64/sc
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x86 --self-contained false -o release/win-x86/lw
          dotnet publish src/WarmCorners.Service/WarmCorners.Service.csproj -p:PublishProfile=windows -c Release -r win-x86 --self-contained true -o release/win-x86/sc

      - name: Zip release files
        run: |
          Compress-Archive -Path release\win-x64\lw\* -DestinationPath release\warm-corners_x64.zip
          Compress-Archive -Path release\win-x64\sc\* -DestinationPath release\warm-corners_x64_sc.zip
          Compress-Archive -Path release\win-x86\lw\* -DestinationPath release\warm-corners_x86.zip
          Compress-Archive -Path release\win-x86\sc\* -DestinationPath release\warm-corners_x86_sc.zip

      - name: Create release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            release/warm-corners_x64.zip
            release/warm-corners_x64_sc.zip
            release/warm-corners_x86.zip
            release/warm-corners_x86_sc.zip
